env:
  EXECUTABLES: 'raytracer'

name: CPP-Compilation
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
    paths:
      - '**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
    paths:
      - '**'

jobs:
  check_program_compilation:
    name: "Check program compilation"
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:devel
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Build project
        timeout-minutes: 2
        run: ./shell/cmpRelease.sh
      - name: Check executables
        shell: bash
        run: |
          exit_code=0
          
          IFS=', ' read -r -a array <<< "$EXECUTABLES"
          
          for element in "${array[@]}"
          do
              if [[ ! -f "$element" ]]; then
                  echo ::error title=$element does not exist::The file $element does not exist.
                  exit_code=1
              fi
              if [[ ! -x "$element" ]]; then
                  echo ::error title=$element is not executable::The file $element cant be executed.
                  exit_code=1
              fi
          done
          
          exit $exit_code
