name: CPP-Norm
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
    paths:
      - '**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
    paths:
      - '**'

jobs:
  check_coding_style:
    name: "Check coding style"
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Run coding style checker
        run: |
          check.sh "$(pwd)" "$(pwd)"
          tmpfile=$(mktemp)
          
          echo "0" > "$tmpfile"
          cat coding-style-reports.log | while read -r line; do
            file=$(echo "$line" | cut -d':' -f1 | cut -d'/' -f 2-)
            nbline=$(echo "$line" | cut -d':' -f2)
            title=$(echo "$line" | cut -d':' -f3)" coding style error"
            code=$(echo "$line" | cut -d':' -f4)
            echo "::error title=$title,file=$file,line=$nbline,col=0::$code"
            echo "1" > "$tmpfile"
          done
          
          if [ "$(cat "$tmpfile")" = "1" ]; then
            rm "$tmpfile"
            exit 1
          fi
          rm "$tmpfile"
  cpplint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install cpplint
        run: |
          python -m pip install --upgrade pip
          pip install cpplint

      - name: Run cpplint
        run: |
          cpplint --config .cppRules $(find . -type f \( -name "*.cpp" -or -name "*.h" \) ! -path "./cmake-build*" ! -path "./my-build-debug*")